function toggleCard(cardId) {
  var card = document.getElementById(cardId);
  if (!card) return;
  card.classList.toggle('expanded');
}

var timelineData = [
  {
    name: "Pre-Phagocytosis",
    markers: [
      { label: "Rab5 — cytosolic", type: "" },
      { label: "Rab7 — cytosolic", type: "" },
      { label: "LAMP1 — lysosomal", type: "" },
      { label: "Actin — cortical", type: "present" }
    ],
    changes: [
      "Receptor recognition (Fc-γR, CR3, mannose receptor) initiates signaling",
      "PI3K activation generates PI(4,5)P2 at the phagocytic cup",
      "Rac1 and Cdc42 trigger actin nucleation via Arp2/3 and formins",
      "Local membrane curvature driven by BAR-domain proteins"
    ],
    pathogens: [
      "Shigella (T3SS IpaB/C): begins translocon insertion before full internalization",
      "Listeria (InlA/InlB): triggers PI3K→Rac1 via Met receptor signaling",
      "Salmonella (SopE, SipA): activates Rac1/Cdc42 for actin ruffle formation"
    ]
  },
  {
    name: "Phagosome Formation",
    markers: [
      { label: "Rab5 — being recruited", type: "present" },
      { label: "LAMP1 — absent", type: "absent" },
      { label: "PI(3)P — being generated", type: "present" },
      { label: "EEA1 — absent", type: "absent" }
    ],
    changes: [
      "Pseudopod zippering seals around particle; plasma membrane pinches off",
      "PI(4,5)P2 converted to PI(3)P by class III PI3K (VPS34)",
      "Rab5 anchors to nascent phagosomal membrane",
      "Actin coat begins depolymerizing from sealed vacuole"
    ],
    pathogens: [
      "Listeria: LLO begins inserting into the forming phagosomal membrane",
      "Shigella: IpaB pore formation begins; may escape before full sealing",
      "Legionella: Dot/Icm T4SS begins effector translocation immediately upon entry"
    ]
  },
  {
    name: "Early Phagosome",
    markers: [
      { label: "Rab5 ✓", type: "present" },
      { label: "EEA1 ✓", type: "present" },
      { label: "Rab7 — absent", type: "absent" },
      { label: "LAMP1 — absent", type: "absent" }
    ],
    changes: [
      "pH ~6.5 — mildly acidic, V-ATPase partly active",
      "Early endosome fusion delivers transferrin receptor, recycling cargo",
      "PI(3)P enrichment recruits FYVE-domain effectors (EEA1, Rabenosyn-5)",
      "Rab5 effector complex (hVPS34/p150) maintains PI(3)P and compartment identity"
    ],
    pathogens: [
      "M. tuberculosis: SapM dephosphorylates PI(3)P; blocks Rab5→Rab7 switch",
      "Salmonella SPI-1: early SCV acquires Rab5 transiently; SPI-2 effectors then redirect",
      "Legionella: LCV rapidly acquires ER markers instead of early endosomal markers via DrrA/SidM"
    ]
  },
  {
    name: "Late Phagosome",
    markers: [
      { label: "Rab7 ✓", type: "present" },
      { label: "LAMP1 ✓", type: "present" },
      { label: "Rab5 — absent/decreasing", type: "absent" },
      { label: "V-ATPase ✓", type: "present" }
    ],
    changes: [
      "pH ~5.5 — significant acidification via V-ATPase",
      "Rab5→Rab7 switch mediated by Mon1–CCZ1 GEF complex",
      "LAMP1 acquisition via late endosome fusion",
      "Cathepsin D, cathepsin B begin import but remain largely inactive",
      "RILP recruits dynein; vacuole moves toward perinuclear lysosomes"
    ],
    pathogens: [
      "Salmonella: SifA/SKIP decouples LAMP1 acquisition from functional maturation",
      "Salmonella: SseJ deacylates membrane cholesterol to maintain SCV identity",
      "M. tuberculosis: tlyA and other lipids prevent full V-ATPase recruitment; pH stays ~6.4"
    ]
  },
  {
    name: "Phagolysosome",
    markers: [
      { label: "LAMP1 ✓✓", type: "present" },
      { label: "Cathepsins ✓", type: "present" },
      { label: "Rab7 — decreasing", type: "" },
      { label: "pH ~4.5", type: "present" }
    ],
    changes: [
      "pH ~4.5 — fully acidified; optimal for hydrolase activity",
      "Cathepsin B, D, L, S cleave proteins; lipases degrade bacterial membranes",
      "Reactive Oxygen Species (ROS) generated by NADPH oxidase",
      "Reactive Nitrogen Species (RNS) via iNOS contribute to killing",
      "Bactericidal peptides (defensins, lactoferricin) concentrated in lumen"
    ],
    pathogens: [
      "Most pathogens that reach this stage are killed — this is the canonical endpoint",
      "Coxiella burnetii (not profiled): uniquely thrives IN the phagolysosome at pH 4.5",
      "Pathogens like Mtb, Salmonella, Legionella act upstream to never reach this stage"
    ]
  }
];

var activeStage = null;

function activateStage(index) {
  var stages = document.querySelectorAll('.timeline-stage');
  var detail = document.getElementById('timeline-detail');

  if (activeStage === index) {
    stages[index].classList.remove('active');
    detail.classList.remove('visible');
    activeStage = null;
    return;
  }

  if (activeStage !== null) {
    stages[activeStage].classList.remove('active');
  }

  stages[index].classList.add('active');
  activeStage = index;

  var data = timelineData[index];

  document.getElementById('detail-stage-name').textContent = data.name;

  var markersEl = document.getElementById('detail-markers');
  markersEl.innerHTML = '';
  data.markers.forEach(function(m) {
    var tag = document.createElement('span');
    tag.className = 'marker-tag' + (m.type ? ' ' + m.type : '');
    tag.textContent = m.label;
    markersEl.appendChild(tag);
  });

  var changesEl = document.getElementById('detail-changes');
  changesEl.innerHTML = '';
  data.changes.forEach(function(c) {
    var li = document.createElement('li');
    li.textContent = c;
    changesEl.appendChild(li);
  });

  var pathEl = document.getElementById('detail-pathogens');
  pathEl.innerHTML = '';
  data.pathogens.forEach(function(p) {
    var li = document.createElement('li');
    li.textContent = p;
    pathEl.appendChild(li);
  });

  detail.classList.add('visible');

  setTimeout(function() {
    detail.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }, 80);
}

function closeTimeline() {
  var stages = document.querySelectorAll('.timeline-stage');
  var detail = document.getElementById('timeline-detail');

  if (activeStage !== null) {
    stages[activeStage].classList.remove('active');
    activeStage = null;
  }
  detail.classList.remove('visible');
}
