function toggleCard(cardId) {
  var card = document.getElementById(cardId);
  if (!card) return;
  card.classList.toggle('expanded');
}

var timelineData = [
  {
    name: "Pre-Phagocytosis",
    markers: [
      { label: "Rab5 — cytosolic", type: "" },
      { label: "Rab7 — cytosolic", type: "" },
      { label: "LAMP1 — lysosomal", type: "" },
      { label: "Actin — cortical", type: "present" }
    ],
    changes: [
      "Receptor recognition (Fc-γR, CR3, mannose receptor) initiates signaling",
      "PI3K activation generates PI(4,5)P2 at the phagocytic cup",
      "Rac1 and Cdc42 trigger actin nucleation via Arp2/3 and formins",
      "Local membrane curvature driven by BAR-domain proteins"
    ],
    pathogens: [
      "Shigella (T3SS IpaB/C): begins translocon insertion before full internalization",
      "Listeria (InlA/InlB): triggers PI3K→Rac1 via Met receptor signaling",
      "Salmonella (SopE, SipA): activates Rac1/Cdc42 for actin ruffle formation"
    ]
  },
  {
    name: "Phagosome Formation",
    markers: [
      { label: "Rab5 — being recruited", type: "present" },
      { label: "LAMP1 — absent", type: "absent" },
      { label: "PI(3)P — being generated", type: "present" },
      { label: "EEA1 — absent", type: "absent" }
    ],
    changes: [
      "Pseudopod zippering seals around particle; plasma membrane pinches off",
      "PI(4,5)P2 converted to PI(3)P by class III PI3K (VPS34)",
      "Rab5 anchors to nascent phagosomal membrane",
      "Actin coat begins depolymerizing from sealed vacuole"
    ],
    pathogens: [
      "Listeria: LLO begins inserting into the forming phagosomal membrane",
      "Shigella: IpaB pore formation begins; may escape before full sealing",
      "Legionella: Dot/Icm T4SS begins effector translocation immediately upon entry"
    ]
  },
  {
    name: "Early Phagosome",
    markers: [
      { label: "Rab5 ✓", type: "present" },
      { label: "EEA1 ✓", type: "present" },
      { label: "Rab7 — absent", type: "absent" },
      { label: "LAMP1 — absent", type: "absent" }
    ],
    changes: [
      "pH ~6.5 — mildly acidic, V-ATPase partly active",
      "Early endosome fusion delivers transferrin receptor, recycling cargo",
      "PI(3)P enrichment recruits FYVE-domain effectors (EEA1, Rabenosyn-5)",
      "Rab5 effector complex (hVPS34/p150) maintains PI(3)P and compartment identity"
    ],
    pathogens: [
      "M. tuberculosis: SapM dephosphorylates PI(3)P; blocks Rab5→Rab7 switch",
      "Salmonella SPI-1: early SCV acquires Rab5 transiently; SPI-2 effectors then redirect",
      "Legionella: LCV rapidly acquires ER markers instead of early endosomal markers via DrrA/SidM"
    ]
  },
  {
    name: "Late Phagosome",
    markers: [
      { label: "Rab7 ✓", type: "present" },
      { label: "LAMP1 ✓", type: "present" },
      { label: "Rab5 — absent/decreasing", type: "absent" },
      { label: "V-ATPase ✓", type: "present" }
    ],
    changes: [
      "pH ~5.5 — significant acidification via V-ATPase",
      "Rab5→Rab7 switch mediated by Mon1–CCZ1 GEF complex",
      "LAMP1 acquisition via late endosome fusion",
      "Cathepsin D, cathepsin B begin import but remain largely inactive",
      "RILP recruits dynein; vacuole moves toward perinuclear lysosomes"
    ],
    pathogens: [
      "Salmonella: SifA/SKIP decouples LAMP1 acquisition from functional maturation",
      "Salmonella: SseJ deacylates membrane cholesterol to maintain SCV identity",
      "M. tuberculosis: tlyA and other lipids prevent full V-ATPase recruitment; pH stays ~6.4"
    ]
  },
  {
    name: "Phagolysosome",
    markers: [
      { label: "LAMP1 ✓✓", type: "present" },
      { label: "Cathepsins ✓", type: "present" },
      { label: "Rab7 — decreasing", type: "" },
      { label: "pH ~4.5", type: "present" }
    ],
    changes: [
      "pH ~4.5 — fully acidified; optimal for hydrolase activity",
      "Cathepsin B, D, L, S cleave proteins; lipases degrade bacterial membranes",
      "Reactive Oxygen Species (ROS) generated by NADPH oxidase",
      "Reactive Nitrogen Species (RNS) via iNOS contribute to killing",
      "Bactericidal peptides (defensins, lactoferricin) concentrated in lumen"
    ],
    pathogens: [
      "Most pathogens that reach this stage are killed — this is the canonical endpoint",
      "Coxiella burnetii (not profiled): uniquely thrives IN the phagolysosome at pH 4.5",
      "Pathogens like Mtb, Salmonella, Legionella act upstream to never reach this stage"
    ]
  }
];

var activeStage = null;

function activateStage(index) {
  var stages = document.querySelectorAll('.timeline-stage');
  var detail = document.getElementById('timeline-detail');

  if (activeStage === index) {
    stages[index].classList.remove('active');
    detail.classList.remove('visible');
    activeStage = null;
    return;
  }

  if (activeStage !== null) {
    stages[activeStage].classList.remove('active');
  }

  stages[index].classList.add('active');
  activeStage = index;

  var data = timelineData[index];

  document.getElementById('detail-stage-name').textContent = data.name;

  var markersEl = document.getElementById('detail-markers');
  markersEl.innerHTML = '';
  var map = _getProteinPathogens();
  data.markers.forEach(function(m) {
    var tag = document.createElement('span');
    tag.className = 'marker-tag' + (m.type ? ' ' + m.type : '');
    tag.textContent = m.label;
    // Check if this label matches a known host protein
    var label = m.label;
    var matched = false;
    var keys = Object.keys(map);
    for (var k = 0; k < keys.length; k++) {
      if (label.indexOf(keys[k]) !== -1) {
        tag.style.cursor = "pointer";
        tag.title = "Click to see which pathogens target " + keys[k];
        (function(prot) {
          tag.addEventListener("click", function(e) {
            e.stopPropagation();
            _showMarkerPathogens(prot, tag);
          });
        })(keys[k]);
        matched = true;
        break;
      }
    }
    markersEl.appendChild(tag);
  });

  var changesEl = document.getElementById('detail-changes');
  changesEl.innerHTML = '';
  data.changes.forEach(function(c) {
    var li = document.createElement('li');
    li.textContent = c;
    changesEl.appendChild(li);
  });

  var pathEl = document.getElementById('detail-pathogens');
  pathEl.innerHTML = '';
  data.pathogens.forEach(function(p) {
    var li = document.createElement('li');
    li.textContent = p;
    pathEl.appendChild(li);
  });

  detail.classList.add('visible');

  setTimeout(function() {
    detail.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }, 80);
}

function closeTimeline() {
  var stages = document.querySelectorAll('.timeline-stage');
  var detail = document.getElementById('timeline-detail');

  if (activeStage !== null) {
    stages[activeStage].classList.remove('active');
    activeStage = null;
  }
  detail.classList.remove('visible');
  var info = document.getElementById("marker-pathogen-info");
  if (info) info.style.display = "none";
}

// Build host protein → pathogens lookup from effectors data
var _proteinPathogens = null;
function _getProteinPathogens() {
  if (_proteinPathogens) return _proteinPathogens;
  _proteinPathogens = {};
  TOOLKIT_DATA.effectors.forEach(function(e) {
    var targets = [e.host_target];
    // Some effectors list multiple targets separated by " / " or "and"
    if (e.host_target) {
      targets = e.host_target.split(/ \/ | and /);
    }
    targets.forEach(function(t) {
      var key = t.trim();
      if (!key) return;
      if (!_proteinPathogens[key]) _proteinPathogens[key] = [];
      if (_proteinPathogens[key].indexOf(e.pathogen_name) === -1) {
        _proteinPathogens[key].push(e.pathogen_name);
      }
    });
  });
  return _proteinPathogens;
}

function _showMarkerPathogens(proteinName, el) {
  var map = _getProteinPathogens();
  var info = document.getElementById("marker-pathogen-info");
  if (!info) return;

  // Try exact match first, then partial
  var pathogens = map[proteinName];
  if (!pathogens || !pathogens.length) {
    // Try partial match: find a key contained in proteinName
    var keys = Object.keys(map);
    for (var i = 0; i < keys.length; i++) {
      if (proteinName.indexOf(keys[i]) !== -1) {
        pathogens = map[keys[i]];
        break;
      }
    }
  }
  if (!pathogens || !pathogens.length) {
    info.style.display = "none";
    return;
  }

  el.classList.add("clicked");
  info.innerHTML = "<div class='marker-pathogen-header'><strong>Pathogens targeting this marker:</strong> <span class='marker-pathogen-close' onclick='_hideMarkerPathogens()'>&times;</span></div>"
    + "<ul>" + pathogens.map(function(p) { return "<li>" + p + "</li>"; }).join("") + "</ul>";
  info.style.display = "block";
}

function _hideMarkerPathogens() {
  var info = document.getElementById("marker-pathogen-info");
  if (info) info.style.display = "none";
  var tags = document.querySelectorAll(".marker-tag.clicked");
  tags.forEach(function(t) { t.classList.remove("clicked"); });
}

/* ---------------------------------------------------------------------------
   Toolkit — fully offline with embedded data; API is optional enhancement
   --------------------------------------------------------------------------- */

function _buildMarkerProfiles() {
  var profiles = {};
  TOOLKIT_DATA.stage_markers.forEach(function(sm) {
    if (!profiles[sm.stage_name]) profiles[sm.stage_name] = {};
    profiles[sm.stage_name][sm.host_protein_name] = sm.presence;
  });
  return profiles;
}

var _STAGE_PROFILES = null;
function _getStageProfiles() {
  if (!_STAGE_PROFILES) _STAGE_PROFILES = _buildMarkerProfiles();
  return _STAGE_PROFILES;
}

function initToolkit() {
  var pSel = document.getElementById("pathogen-select");
  var mSel = document.getElementById("ml-pathogen-select");
  if (!pSel && !mSel) return;

  var opts = TOOLKIT_DATA.pathogens.map(function(p) {
    return '<option value="' + p.name + '">' + p.name + ' (' + p.strategy + ')</option>';
  }).join("");
  if (pSel) pSel.insertAdjacentHTML("beforeend", opts);
  if (mSel && mSel !== pSel) mSel.insertAdjacentHTML("beforeend", opts);

  var checklist = document.getElementById("marker-checklist");
  if (checklist) {
    checklist.innerHTML = TOOLKIT_DATA.stage_marker_names.map(function(m) {
      return '<label><input type="checkbox" value="' + m + '"> ' + m + '</label>';
    }).join("");
  }
}

function showError(elId, msg) {
  var el = document.getElementById(elId);
  if (!el) return;
  el.innerHTML = '<div class="error">' + msg + '</div>';
}

var _currentEffectors = [];

function _renderEffectorTable(rows, el) {
  if (!rows.length) { el.innerHTML = "<em>No effectors match the filter.</em>"; return; }
  var html = "<table><thead><tr><th>Effector</th><th>Type</th><th>Host Target</th><th>Mechanism</th></tr></thead><tbody>";
  rows.forEach(function(e) {
    html += "<tr><td>" + e.effector_name + "</td><td>" + (e.type || "—") + "</td><td>" + (e.host_target || "—") + "</td><td>" + (e.mechanism || "—") + "</td></tr>";
  });
  html += "</tbody></table>";
  el.innerHTML = html;
}

function loadPathogenEffectors() {
  var sel = document.getElementById("pathogen-select");
  var name = sel ? sel.value : "";
  if (!name) { showError("pathogen-result", "Select a pathogen first."); return; }

  _currentEffectors = TOOLKIT_DATA.effectors.filter(function(e) {
    return e.pathogen_name === name;
  });

  var el = document.getElementById("pathogen-result");
  if (!el) return;
  if (!_currentEffectors.length) { el.innerHTML = "<em>No effectors found for " + name + ".</em>"; return; }

  var searchEl = document.getElementById("effector-search");
  if (searchEl) { searchEl.value = ""; searchEl.style.display = "block"; searchEl.placeholder = "Filter " + _currentEffectors.length + " effectors…"; }
  var dlBtn = document.getElementById("dl-effectors-btn");
  if (dlBtn) dlBtn.style.display = "inline-block";

  _renderEffectorTable(_currentEffectors, el);
}

function filterEffectors() {
  var searchEl = document.getElementById("effector-search");
  var q = searchEl ? searchEl.value.toLowerCase() : "";
  var filtered = _currentEffectors.filter(function(e) {
    return e.effector_name.toLowerCase().indexOf(q) !== -1
        || (e.type || "").toLowerCase().indexOf(q) !== -1
        || (e.host_target || "").toLowerCase().indexOf(q) !== -1
        || (e.mechanism || "").toLowerCase().indexOf(q) !== -1;
  });
  var el = document.getElementById("pathogen-result");
  if (el) _renderEffectorTable(filtered, el);
}

function _stageResultFallback(observed, el) {
  var profiles = _getStageProfiles();
  var best = null, bestScore = -1;

  Object.keys(profiles).forEach(function(stage) {
    var profile = profiles[stage];
    var match = 0, total = 0;
    Object.keys(profile).forEach(function(marker) {
      if (observed[marker] !== undefined) {
        total++;
        if (observed[marker] === profile[marker]) match++;
      }
    });
    if (total > 0) {
      var score = match / total;
      if (score > bestScore) { bestScore = score; best = stage; }
    }
  });

  if (!best) {
    el.innerHTML = "<em>No matching stage. Try selecting different markers.</em>";
    return;
  }
  el.innerHTML = "<strong>Predicted stage:</strong> "
    + '<span class="badge badge-blue">' + best + "</span>"
    + " &nbsp;(confidence: " + (bestScore * 100).toFixed(0) + "%)";
}

function predictStage() {
  var checked = document.querySelectorAll("#marker-checklist input:checked");
  var markers = Array.from(checked).map(function(cb) { return cb.value; });

  if (!markers.length) { showError("stage-result", "Select at least one marker."); return; }

  var el = document.getElementById("stage-result");
  if (!el) return;
  el.innerHTML = "<em>Predicting…</em>";

  fetch("/api/trafficking/predict-stage", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ markers: markers })
  })
  .then(function(r) { if (!r.ok) throw new Error("API unavailable"); return r.json(); })
  .then(function(info) {
    var present = (info.markers_present || []).join(", ");
    el.innerHTML = "<strong>Predicted stage:</strong> "
      + '<span class="badge badge-blue">' + info.name + "</span>"
      + "<br><small>pH " + info.ph_min + "–" + info.ph_max
      + " · " + info.time_range
      + " · Markers: " + present + "</small>";
  })
  .catch(function() {
    var observed = {};
    markers.forEach(function(m) { observed[m] = 1; });
    _stageResultFallback(observed, el);
  });
}

function loadHubProteins() {
  var data = TOOLKIT_DATA.hubs;
  var el = document.getElementById("hub-result");
  if (!el) return;
  if (!data.length) { el.innerHTML = "<em>No hub data available.</em>"; return; }
  var html = "<table><thead><tr><th>#</th><th>Host Protein</th><th>Degree</th><th>Centrality</th></tr></thead><tbody>";
  data.forEach(function(h, i) {
    html += "<tr><td>" + (i+1) + "</td><td>" + h.host + "</td><td>" + h.degree + "</td><td>" + h.centrality.toFixed(4) + "</td></tr>";
  });
  html += "</tbody></table>";
  el.innerHTML = html;
  var dlBtn = document.getElementById("dl-hubs-btn");
  if (dlBtn) dlBtn.style.display = "inline-block";
}

function predictStrategy() {
  var sel = document.getElementById("ml-pathogen-select");
  var name = sel ? sel.value : "";
  if (!name) { showError("ml-result", "Select a pathogen first."); return; }

  var match = null;
  for (var i = 0; i < TOOLKIT_DATA.ml_predictions.length; i++) {
    if (TOOLKIT_DATA.ml_predictions[i].pathogen === name) {
      match = TOOLKIT_DATA.ml_predictions[i];
      break;
    }
  }

  var el = document.getElementById("ml-result");
  if (!el) return;
  if (!match) { el.innerHTML = "<em>No prediction available for " + name + ".</em>"; return; }

  var predicted = match.predicted;
  var actual = match.actual;
  var ok = predicted === actual ? "green" : "red";
  el.innerHTML = "<strong>Predicted:</strong> <span class='badge badge-" + ok + "'>" + predicted + "</span>"
    + " &nbsp;| <strong>Actual:</strong> <span class='badge badge-blue'>" + actual + "</span>"
    + " &nbsp;(confidence: " + (match.confidence * 100).toFixed(0) + "%)";
}

function _downloadCSV(rows, columns, filename) {
  var header = columns.map(function(c) { return '"' + c.label + '"'; }).join(",");
  var data = rows.map(function(r) {
    return columns.map(function(c) { var v = r[c.key]; return '"' + (v || "").replace(/"/g, '""') + '"'; }).join(",");
  }).join("\n");
  var blob = new Blob([header + "\n" + data], { type: "text/csv;charset=utf-8;" });
  var link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

function downloadEffectorsCSV() {
  if (!_currentEffectors.length) return;
  _downloadCSV(_currentEffectors, [
    { key: "effector_name", label: "Effector" },
    { key: "type", label: "Type" },
    { key: "host_target", label: "Host Target" },
    { key: "mechanism", label: "Mechanism" }
  ], "effectors.csv");
}

function downloadHubsCSV() {
  var data = TOOLKIT_DATA.hubs;
  if (!data.length) return;
  _downloadCSV(data, [
    { key: "host", label: "Host Protein" },
    { key: "degree", label: "Degree" },
    { key: "centrality", label: "Centrality" }
  ], "hub_proteins.csv");
}

document.addEventListener("DOMContentLoaded", initToolkit);
