function toggleCard(cardId) {
  var card = document.getElementById(cardId);
  if (!card) return;
  card.classList.toggle('expanded');
}

var timelineData = [
  {
    name: "Pre-Phagocytosis",
    markers: [
      { label: "Rab5 — cytosolic", type: "" },
      { label: "Rab7 — cytosolic", type: "" },
      { label: "LAMP1 — lysosomal", type: "" },
      { label: "Actin — cortical", type: "present" }
    ],
    changes: [
      "Receptor recognition (Fc-γR, CR3, mannose receptor) initiates signaling",
      "PI3K activation generates PI(4,5)P2 at the phagocytic cup",
      "Rac1 and Cdc42 trigger actin nucleation via Arp2/3 and formins",
      "Local membrane curvature driven by BAR-domain proteins"
    ],
    pathogens: [
      "Shigella (T3SS IpaB/C): begins translocon insertion before full internalization",
      "Listeria (InlA/InlB): triggers PI3K→Rac1 via Met receptor signaling",
      "Salmonella (SopE, SipA): activates Rac1/Cdc42 for actin ruffle formation"
    ]
  },
  {
    name: "Phagosome Formation",
    markers: [
      { label: "Rab5 — being recruited", type: "present" },
      { label: "LAMP1 — absent", type: "absent" },
      { label: "PI(3)P — being generated", type: "present" },
      { label: "EEA1 — absent", type: "absent" }
    ],
    changes: [
      "Pseudopod zippering seals around particle; plasma membrane pinches off",
      "PI(4,5)P2 converted to PI(3)P by class III PI3K (VPS34)",
      "Rab5 anchors to nascent phagosomal membrane",
      "Actin coat begins depolymerizing from sealed vacuole"
    ],
    pathogens: [
      "Listeria: LLO begins inserting into the forming phagosomal membrane",
      "Shigella: IpaB pore formation begins; may escape before full sealing",
      "Legionella: Dot/Icm T4SS begins effector translocation immediately upon entry"
    ]
  },
  {
    name: "Early Phagosome",
    markers: [
      { label: "Rab5 ✓", type: "present" },
      { label: "EEA1 ✓", type: "present" },
      { label: "Rab7 — absent", type: "absent" },
      { label: "LAMP1 — absent", type: "absent" }
    ],
    changes: [
      "pH ~6.5 — mildly acidic, V-ATPase partly active",
      "Early endosome fusion delivers transferrin receptor, recycling cargo",
      "PI(3)P enrichment recruits FYVE-domain effectors (EEA1, Rabenosyn-5)",
      "Rab5 effector complex (hVPS34/p150) maintains PI(3)P and compartment identity"
    ],
    pathogens: [
      "M. tuberculosis: SapM dephosphorylates PI(3)P; blocks Rab5→Rab7 switch",
      "Salmonella SPI-1: early SCV acquires Rab5 transiently; SPI-2 effectors then redirect",
      "Legionella: LCV rapidly acquires ER markers instead of early endosomal markers via DrrA/SidM"
    ]
  },
  {
    name: "Late Phagosome",
    markers: [
      { label: "Rab7 ✓", type: "present" },
      { label: "LAMP1 ✓", type: "present" },
      { label: "Rab5 — absent/decreasing", type: "absent" },
      { label: "V-ATPase ✓", type: "present" }
    ],
    changes: [
      "pH ~5.5 — significant acidification via V-ATPase",
      "Rab5→Rab7 switch mediated by Mon1–CCZ1 GEF complex",
      "LAMP1 acquisition via late endosome fusion",
      "Cathepsin D, cathepsin B begin import but remain largely inactive",
      "RILP recruits dynein; vacuole moves toward perinuclear lysosomes"
    ],
    pathogens: [
      "Salmonella: SifA/SKIP decouples LAMP1 acquisition from functional maturation",
      "Salmonella: SseJ deacylates membrane cholesterol to maintain SCV identity",
      "M. tuberculosis: tlyA and other lipids prevent full V-ATPase recruitment; pH stays ~6.4"
    ]
  },
  {
    name: "Phagolysosome",
    markers: [
      { label: "LAMP1 ✓✓", type: "present" },
      { label: "Cathepsins ✓", type: "present" },
      { label: "Rab7 — decreasing", type: "" },
      { label: "pH ~4.5", type: "present" }
    ],
    changes: [
      "pH ~4.5 — fully acidified; optimal for hydrolase activity",
      "Cathepsin B, D, L, S cleave proteins; lipases degrade bacterial membranes",
      "Reactive Oxygen Species (ROS) generated by NADPH oxidase",
      "Reactive Nitrogen Species (RNS) via iNOS contribute to killing",
      "Bactericidal peptides (defensins, lactoferricin) concentrated in lumen"
    ],
    pathogens: [
      "Most pathogens that reach this stage are killed — this is the canonical endpoint",
      "Coxiella burnetii (not profiled): uniquely thrives IN the phagolysosome at pH 4.5",
      "Pathogens like Mtb, Salmonella, Legionella act upstream to never reach this stage"
    ]
  }
];

var activeStage = null;

function activateStage(index) {
  var stages = document.querySelectorAll('.timeline-stage');
  var detail = document.getElementById('timeline-detail');

  if (activeStage === index) {
    stages[index].classList.remove('active');
    detail.classList.remove('visible');
    activeStage = null;
    return;
  }

  if (activeStage !== null) {
    stages[activeStage].classList.remove('active');
  }

  stages[index].classList.add('active');
  activeStage = index;

  var data = timelineData[index];

  document.getElementById('detail-stage-name').textContent = data.name;

  var markersEl = document.getElementById('detail-markers');
  markersEl.innerHTML = '';
  data.markers.forEach(function(m) {
    var tag = document.createElement('span');
    tag.className = 'marker-tag' + (m.type ? ' ' + m.type : '');
    tag.textContent = m.label;
    markersEl.appendChild(tag);
  });

  var changesEl = document.getElementById('detail-changes');
  changesEl.innerHTML = '';
  data.changes.forEach(function(c) {
    var li = document.createElement('li');
    li.textContent = c;
    changesEl.appendChild(li);
  });

  var pathEl = document.getElementById('detail-pathogens');
  pathEl.innerHTML = '';
  data.pathogens.forEach(function(p) {
    var li = document.createElement('li');
    li.textContent = p;
    pathEl.appendChild(li);
  });

  detail.classList.add('visible');

  setTimeout(function() {
    detail.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }, 80);
}

function closeTimeline() {
  var stages = document.querySelectorAll('.timeline-stage');
  var detail = document.getElementById('timeline-detail');

  if (activeStage !== null) {
    stages[activeStage].classList.remove('active');
    activeStage = null;
  }
  detail.classList.remove('visible');
}

/* ---------------------------------------------------------------------------
   Toolkit — fully offline with embedded data; API is optional enhancement
   --------------------------------------------------------------------------- */

function _buildMarkerProfiles() {
  var profiles = {};
  TOOLKIT_DATA.stage_markers.forEach(function(sm) {
    if (!profiles[sm.stage_name]) profiles[sm.stage_name] = {};
    profiles[sm.stage_name][sm.host_protein_name] = sm.presence;
  });
  return profiles;
}

var _STAGE_PROFILES = null;
function _getStageProfiles() {
  if (!_STAGE_PROFILES) _STAGE_PROFILES = _buildMarkerProfiles();
  return _STAGE_PROFILES;
}

function initToolkit() {
  var pSel = document.getElementById("pathogen-select");
  var mSel = document.getElementById("ml-pathogen-select");
  if (!pSel && !mSel) return;

  var opts = TOOLKIT_DATA.pathogens.map(function(p) {
    return '<option value="' + p.name + '">' + p.name + ' (' + p.strategy + ')</option>';
  }).join("");
  if (pSel) pSel.insertAdjacentHTML("beforeend", opts);
  if (mSel && mSel !== pSel) mSel.insertAdjacentHTML("beforeend", opts);

  var checklist = document.getElementById("marker-checklist");
  if (checklist) {
    checklist.innerHTML = TOOLKIT_DATA.stage_marker_names.map(function(m) {
      return '<label><input type="checkbox" value="' + m + '"> ' + m + '</label>';
    }).join("");
  }
}

function showError(elId, msg) {
  var el = document.getElementById(elId);
  if (!el) return;
  el.innerHTML = '<div class="error">' + msg + '</div>';
}

function loadPathogenEffectors() {
  var sel = document.getElementById("pathogen-select");
  var name = sel ? sel.value : "";
  if (!name) { showError("pathogen-result", "Select a pathogen first."); return; }

  var rows = TOOLKIT_DATA.effectors.filter(function(e) {
    return e.pathogen_name === name;
  });

  var el = document.getElementById("pathogen-result");
  if (!el) return;
  if (!rows.length) { el.innerHTML = "<em>No effectors found for " + name + ".</em>"; return; }
  var html = "<table><thead><tr><th>Effector</th><th>Type</th><th>Host Target</th><th>Mechanism</th></tr></thead><tbody>";
  rows.forEach(function(e) {
    html += "<tr><td>" + e.effector_name + "</td><td>" + (e.type || "—") + "</td><td>" + (e.host_target || "—") + "</td><td>" + (e.mechanism || "—") + "</td></tr>";
  });
  html += "</tbody></table>";
  el.innerHTML = html;
}

function predictStage() {
  var checked = document.querySelectorAll("#marker-checklist input:checked");
  var observed = {};
  Array.from(checked).forEach(function(cb) { observed[cb.value] = 1; });

  if (!Object.keys(observed).length) { showError("stage-result", "Select at least one marker."); return; }

  var profiles = _getStageProfiles();
  var best = null, bestScore = -1;

  Object.keys(profiles).forEach(function(stage) {
    var profile = profiles[stage];
    var match = 0, total = 0;
    Object.keys(profile).forEach(function(marker) {
      if (observed[marker] !== undefined) {
        total++;
        if (observed[marker] === profile[marker]) match++;
      }
    });
    if (total > 0) {
      var score = match / total;
      if (score > bestScore) { bestScore = score; best = stage; }
    }
  });

  var el = document.getElementById("stage-result");
  if (!el) return;
  if (!best) {
    el.innerHTML = "<em>No matching stage. Try selecting different markers.</em>";
    return;
  }
  el.innerHTML = "<strong>Predicted stage:</strong> "
    + '<span class="badge badge-blue">' + best + "</span>"
    + " &nbsp;(confidence: " + (bestScore * 100).toFixed(0) + "%)";
}

function loadHubProteins() {
  var data = TOOLKIT_DATA.hubs;
  var el = document.getElementById("hub-result");
  if (!el) return;
  if (!data.length) { el.innerHTML = "<em>No hub data available.</em>"; return; }
  var html = "<table><thead><tr><th>#</th><th>Host Protein</th><th>Degree</th><th>Centrality</th></tr></thead><tbody>";
  data.forEach(function(h, i) {
    html += "<tr><td>" + (i+1) + "</td><td>" + h.host + "</td><td>" + h.degree + "</td><td>" + h.centrality.toFixed(4) + "</td></tr>";
  });
  html += "</tbody></table>";
  el.innerHTML = html;
}

function predictStrategy() {
  var sel = document.getElementById("ml-pathogen-select");
  var name = sel ? sel.value : "";
  if (!name) { showError("ml-result", "Select a pathogen first."); return; }

  var match = null;
  for (var i = 0; i < TOOLKIT_DATA.ml_predictions.length; i++) {
    if (TOOLKIT_DATA.ml_predictions[i].pathogen === name) {
      match = TOOLKIT_DATA.ml_predictions[i];
      break;
    }
  }

  var el = document.getElementById("ml-result");
  if (!el) return;
  if (!match) { el.innerHTML = "<em>No prediction available for " + name + ".</em>"; return; }

  var predicted = match.predicted;
  var actual = match.actual;
  var ok = predicted === actual ? "green" : "red";
  el.innerHTML = "<strong>Predicted:</strong> <span class='badge badge-" + ok + "'>" + predicted + "</span>"
    + " &nbsp;| <strong>Actual:</strong> <span class='badge badge-blue'>" + actual + "</span>"
    + " &nbsp;(confidence: " + (match.confidence * 100).toFixed(0) + "%)";
}

document.addEventListener("DOMContentLoaded", initToolkit);
